import React, { useEffect, useState } from 'react';
import { getAdminPayouts, processAdminPayout } from '../../services/api';
const money=(n)=>`₹${Number(n||0).toFixed(2)}`;
export default function WithdrawalDesk() {
  const [data,setData]=useState({data:[]});const [page,setPage]=useState(1);const [filter,setFilter]=useState('');const [selected,setSelected]=useState(null);const [action,setAction]=useState('');const [note,setNote]=useState('');const [ref,setRef]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const load=async()=>{try{const r=await getAdminPayouts({page,status:filter||undefined});setData(r.data.payouts);}catch{setError('Unable to load withdrawals.');}};
  useEffect(()=>{load();},[page,filter]);
  const open=(p,a)=>{setSelected(p);setAction(a);setNote('');setRef('');setError('');};
  const submit=async(e)=>{e.preventDefault();if(busy)return;setBusy(true);try{await processAdminPayout(selected.id,{action,admin_note:note,transaction_ref:ref,failure_confirmed:action==='fail'});setSelected(null);await load();}catch(e){setError(Object.values(e.response?.data?.errors||{}).flat()[0]||e.response?.data?.message||'Unable to update withdrawal.');}finally{setBusy(false);}};
  return <section className="bg-white border rounded-2xl p-5 space-y-4"><h2 className="font-black text-lg">Withdrawal requests</h2><p className="text-sm text-slate-500">Approve, process the bank transfer, then record success with the actual UTR. Approval does not send money.</p><select aria-label="Withdrawal status filter" value={filter} onChange={(e)=>{setFilter(e.target.value);setPage(1);}} className="border rounded-xl p-2">{['','pending','approved','processing','success','rejected','failed'].map(s=><option value={s} key={s}>{s||'All statuses'}</option>)}</select>
    {error&&<p role="alert" className="text-rose-700">{error}</p>}
    {data.data?.map(p=><article key={p.id} className="border rounded-xl p-4 space-y-2 text-sm"><div className="flex justify-between font-bold"><span>#{p.id} · {p.user?.name}</span><span className="capitalize">{p.status}</span></div><p>Gross {money(p.amount)} · TDS (5%) {money(p.admin_fee)} · Bank payout {money(p.net_payable)}</p><details><summary className="cursor-pointer">Review bank details and status history</summary><p className="whitespace-pre-line py-2">{p.account_details}</p>{p.transaction_ref&&<p>UTR: {p.transaction_ref}</p>}{p.events?.map(ev=><p key={ev.id}>{ev.status} · {new Date(ev.created_at).toLocaleString()} · {ev.note}</p>)}</details><div className="flex flex-wrap gap-3">
      {(p.status==='pending'?['approve','reject']:p.status==='approved'?['process','reject']:p.status==='processing'?['success','fail']:[]).map(a=><button key={a} onClick={()=>open(p,a)} className="border rounded-xl px-3 py-2 font-bold">{{approve:'Approve',process:'Start processing',success:'Mark success',reject:'Reject',fail:'Confirm failed transfer'}[a]}</button>)}</div></article>)}
    {!data.data?.length&&<p>No requests found.</p>}
    {data.last_page>1&&<div className="flex gap-4"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>{page} / {data.last_page}</span><button disabled={page>=data.last_page} onClick={()=>setPage(page+1)}>Next</button></div>}
    {selected&&<div role="dialog" aria-modal="true" aria-label="Process withdrawal" className="fixed inset-0 z-[100] bg-black/40 grid place-items-center p-4"><form onSubmit={submit} className="bg-white rounded-2xl p-6 w-full max-w-md space-y-4">{error&&<p role="alert" className="text-rose-700">{error}</p>}<h3 className="font-bold">{action.toUpperCase()} request #{selected.id}</h3><p>Bank payout {money(selected.net_payable)} · TDS {money(selected.admin_fee)}</p>{action==='success'&&<label className="block">Actual bank UTR / reference<input autoFocus required value={ref} onChange={e=>setRef(e.target.value)} className="border rounded-xl p-3 w-full"/></label>}<label className="block">{['reject','fail'].includes(action)?'Reason (required)':'Note'}<textarea required={['reject','fail'].includes(action)} value={note} onChange={e=>setNote(e.target.value)} className="border rounded-xl p-3 w-full"/></label>{action==='fail'&&<p className="text-sm text-rose-700">Confirm only after the bank confirms transfer failure. Reserved funds will be refunded.</p>}<div className="flex gap-4"><button type="button" disabled={busy} onClick={()=>setSelected(null)}>Cancel</button><button disabled={busy} className="bg-brand-blue-800 text-white rounded-xl px-4 py-2">{busy?'Saving…':'Confirm'}</button></div></form></div>}
  </section>;
}
