import React, { useEffect, useRef, useState } from 'react';
import { useParams } from 'react-router-dom';
import html2pdf from 'html2pdf.js';
import { getOrderInvoice } from '../services/api';
const money=(v)=>`₹${Number(v||0).toFixed(2)}`;
export default function InvoiceView() {
  const {id}=useParams();const [data,setData]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const ref=useRef(null);
  useEffect(()=>{let active=true;getOrderInvoice(id).then(r=>{if(active)setData(r.data.invoice);}).catch(e=>{if(active)setError(e.response?.status===403?'Only the buyer and Super Admin can access this invoice.':e.response?.data?.message||'Unable to load invoice.');});return()=>{active=false;};},[id]);
  const download=async()=>{if(busy)return;setBusy(true);try{await html2pdf().set({margin:8,filename:`Invoice-${data.invoice.invoice_no}.pdf`,html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'mm',format:'a4'},pagebreak:{mode:['css','legacy']}}).from(ref.current).save();}catch{setError('Unable to download PDF. You can use Print.');}finally{setBusy(false);}};
  if(!data)return <p role={error?'alert':undefined} className="p-8 text-center">{error||'Loading invoice…'}</p>;
  const {company,customer,invoice,items,financials:f,tax_summary:tax}=data;
  return <main className="max-w-3xl mx-auto p-4"><style>{`@media print { body * { visibility: hidden; } #mg-private-invoice, #mg-private-invoice * { visibility: visible; } #mg-private-invoice { position: absolute; left: 0; top: 0; width: 100%; border: 0; padding: 0; } @page { size: A4; margin: 12mm; } }`}</style><div className="print:hidden flex gap-3 py-3"><button onClick={()=>window.print()} className="border rounded-xl p-2">Print</button><button disabled={busy} onClick={download} className="border rounded-xl p-2">{busy?'Preparing…':'Download PDF'}</button>{error&&<p role="alert">{error}</p>}</div>
    <article id="mg-private-invoice" ref={ref} className="bg-white p-6 border rounded-xl text-sm space-y-5"><header><h1 className="text-xl font-black">{company.name}</h1><p>{company.address}</p><p>GSTIN: {company.gstin} · DL: {company.dl_no}</p></header>
      <section><h2 className="font-bold">Tax Invoice {invoice.invoice_no}</h2><p>{invoice.invoice_date} · Order {invoice.order_no}</p><p className="font-semibold mt-2">Buyer: {customer.name}</p><p>{customer.address}, {customer.city} {customer.pincode}</p><p>Place of supply: {invoice.place_of_supply}</p></section>
      <table className="w-full text-left"><thead><tr className="border-b"><th className="py-2">Medicine / HSN</th><th>Qty</th><th>Rate</th><th className="text-right">Amount</th></tr></thead><tbody>{items.map((i,n)=><tr key={n} className="border-b"><td className="py-3 pr-2">{i.product_name}<p className="text-xs text-slate-500">HSN {i.hsn_code}{i.batch_no&&` · Batch ${i.batch_no}`}{i.expiry_date&&` · Exp ${i.expiry_date}`}</p></td><td>{i.quantity}</td><td>{money(i.final_rate)}</td><td className="text-right">{money(i.total_amount)}</td></tr>)}</tbody></table>
      <section className="text-right space-y-1"><p>Products: {money(f.product_subtotal)}</p><p className="text-xs">Included GST {money(tax.total_tax_amount)} · CGST {money(tax.total_cgst)} · SGST {money(tax.total_sgst)} · IGST {money(tax.total_igst)}</p>{Number(f.discount_amount)>0&&<p>Discount: −{money(f.discount_amount)}</p>}{['delivery_charge','platform_fee','cod_charge'].map(k=>Number(f[k])>0&&<p key={k}>{k.replaceAll('_',' ')}: {money(f[k])}</p>)}<p className="text-lg font-black">Total: {money(f.grand_total)}</p>{Number(f.wallet_used)>0&&<p>Wallet payment: {money(f.wallet_used)}</p>}<p>Payment: {invoice.payment_mode} · {invoice.payment_status}</p><p>Outstanding: {money(f.balance)}</p>{invoice.credit_note_number&&<p>Credit note: {invoice.credit_note_number}</p>}</section>
    </article>
  </main>;
}
